//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPERbr generator.
//

import UIKit

final class ___VARIABLE_moduleName___Presenter {
  
  // MARK: - Private properties  
  private weak var view: ___VARIABLE_moduleName___ViewInterface?
  private let interactor: ___VARIABLE_moduleName___InteractorProtocol
  private let wireframe: ___VARIABLE_moduleName___WireframeInterface
  
  // MARK: - Lifecycle
  init(wireframe: ___VARIABLE_moduleName___WireframeInterface,
       view: ___VARIABLE_moduleName___ViewInterface,
       interactor: ___VARIABLE_moduleName___InteractorProtocol) {
    self.wireframe = wireframe
    self.view = view
    self.interactor = interactor
  }
}

// MARK: - Extensions
extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface { }

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___InteractorResponseProtocol {
  func response___VARIABLE_moduleName___InteractorResponseSuccess(response: ___VARIABLE_moduleName___Model) {
    print(response)
  }

  func response___VARIABLE_moduleName___InteractorResponseError() { }
}